#!/usr/bin/env bash

# all this does is basically put this dir in PATH so we can use 
# deez from wherever
# this script does stuff to your bashrc or zshrc

SCRIPT_DIR=$(dirname "$(realpath $0)")/scripts

add_to_path() {
    if [ $# -ne 1 ]; then
        echo "usage: $0 <shell>"
        echo "supported shells: bash, zsh"
        echo "if you want other shells just put the $SCRIPT_DIR in the rc file"
        exit 1
    fi

    if  ! echo "$PATH" | grep -q "$SCRIPT_DIR"; then
        case "$1" in
            "bash")
                SHELL_CONFIG="$HOME/.bashrc"
                ;;
            "zsh")
                SHELL_CONFIG="$HOME/.zshrc"
                ;;
            *)
                echo "only bash and zsh are supported do stuff with this script to fix that"
                exit 1
                ;;
        esac

cat <<-EOT >> $SHELL_CONFIG

# created by \`$(realpath $0)\` on $(date '+%Y-%m-%d')
export PATH="\$PATH:$SCRIPT_DIR"
EOT

        echo "added $SCRIPT_DIR to PATH in $SHELL_CONFIG"
        echo "now source it by doing \`source $SHELL_CONFIG\`"
    else
        echo "$SCRIPT_DIR is already in PATH, man"
    fi
}

make_executable() {
    chmod +x "$SCRIPT_DIR"/*
}

add_to_path "$@"
make_executable
