#!/usr/bin/env bash

declare -A emoji
emoji[":)"]=😀
emoji[":bear"]=🐻
emoji[":("]=😢

toemoji() {
    while read -r line; do 
        for k in ${!emoji[@]}; do
            line=${line//$k/${emoji[$k]}}
        done
        echo "$line"
    done
}

toemoji "$@"
