#!/usr/bin/env bash

# open a tmux project

tn() {
    session_name=$(basename "$(pwd)")
    session_name="${session_name//./_}"
    if [ -n "$1" ]; then
        session_name="$1-$session_name"
    fi

    tmux new-session -d -s "$session_name" -n editor "nvim"
    tmux new-window -t "$session_name":2
    tmux select-window -t "$session_name:1"

    tmux attach -t "$session_name"
} 

tn "$@"
