#!/usr/bin/env bash

# open a tmux project

tn() {
    if [ -z "$1" ]; then
        session_name="$(basename "$(pwd)")"
    else
        session_name="$1-$(basename "$(pwd)")"
    fi
    tmux new-session -d -s "$session_name" -n editor "nvim"
    tmux new-window -t "$session_name":2
    tmux select-window -t "$session_name:1"

    tmux attach -t "$session_name"
} 

tn "$@"
