#!/usr/bin/env bash

# what dis does, is make todo in $HOME/.todo
# and u can manage deez and so on

todo() {
    local todo_file="./todo"

    if [[ ! -f "$todo_file" ]]; then
        todo_file="$HOME/.todo"
    fi

    if [[ ! -f "$todo_file" ]]; then
        touch "$todo_file"
    fi

    case "$1" in
        "add")
            shift
            if [[ "$#" -ne 1 ]]; then
                echo "todo: man give me a name in quotes \"\""
                return 1
            fi
            echo "- [ ] $1" >> "$todo_file"
            ;;

        "list")
            nl -w 2 -s ". " "$todo_file"
            ;;

        "done")
            shift
            if [[ "$#" -ne 1 || ! "$1" =~ ^[0-9]+$ ]]; then
                echo "todo: specify the task to mark as done!"
                return 1
            fi
            sed "${1}s/\[ \]/[x]/" "$todo_file" > "$todo_file.tmp" && 
                mv "$todo_file.tmp" "$todo_file"
            ;;

        "remove")
            shift
            if [[ "$#" -ne 1 || ! "$1" =~ ^[0-9]+$ ]]; then
                echo "todo: specify the task to remove!"
                return 1
            fi
            sed "${1}d" "$todo_file" > "$todo_file.tmp" && 
                mv "$todo_file.tmp" "$todo_file"
            ;;

        *)
    esac

    if [[ ! $1 ]]; then
        vi "$todo_file"
    fi
}

todo "$@"

