#!/usr/bin/env bash

# make stdin a emoji!!!

declare -A emoji
emoji[":)"]=😀
emoji[":bear"]=🐻
emoji[":("]=😢
emoji[":fire"]=🔥
emoji[":tada"]=🎉
emoji[":lmao"]=😭
emoji[":cat"]=🐱
emoji[":dog"]=🐶
emoji[":panda"]=🐼
emoji[":penguin"]=🐧
emoji[":unicorn"]=🦄
emoji[":skull"]=💀
emoji[":ghost"]=👻
emoji[":robot"]=🤖
emoji[":smile"]=😄
emoji[":thinking"]=🤔

toemoji() {
    while read -r line; do 
        for k in ${!emoji[@]}; do
            line=${line//$k/${emoji[$k]}}
        done
        echo "$line"
    done
}

toemoji "$@"
